// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveAgentsForWorkspace = `-- name: ListActiveAgentsForWorkspace :many
SELECT
  a.id, a.name, a.role, a.model,
  d.name AS machine_name,
  e.status AS runtime_status,
  e.progress_percent,
  e.current_activity
FROM agents a
JOIN LATERAL (
  SELECT id, task_step_id, agent_id, device_id, attempt_number, status, progress_percent, current_activity, started_at, finished_at FROM executions ex
  WHERE ex.agent_id = a.id AND ex.finished_at IS NULL
  ORDER BY ex.started_at DESC
  LIMIT 1
) e ON true
LEFT JOIN devices d ON d.id = e.device_id
WHERE a.workspace_id = $1 AND a.is_active
ORDER BY a.name
`

type ListActiveAgentsForWorkspaceRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Role            AgentRole          `json:"role"`
	Model           string             `json:"model"`
	MachineName     pgtype.Text        `json:"machine_name"`
	RuntimeStatus   AgentRuntimeStatus `json:"runtime_status"`
	ProgressPercent pgtype.Int4        `json:"progress_percent"`
	CurrentActivity string             `json:"current_activity"`
}

func (q *Queries) ListActiveAgentsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListActiveAgentsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgentsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAgentsForWorkspaceRow{}
	for rows.Next() {
		var i ListActiveAgentsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Model,
			&i.MachineName,
			&i.RuntimeStatus,
			&i.ProgressPercent,
			&i.CurrentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
