// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals
SET decision = $2, decided_by_user_id = $3, decided_at = now()
WHERE id = $1
RETURNING id, workspace_id, task_id, execution_id, requested_by_agent_id, title, description, payload, decision, decided_by_user_id, decided_at, created_at
`

type DecideApprovalParams struct {
	ID              uuid.UUID            `json:"id"`
	Decision        NullApprovalDecision `json:"decision"`
	DecidedByUserID uuid.NullUUID        `json:"decided_by_user_id"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval, arg.ID, arg.Decision, arg.DecidedByUserID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ExecutionID,
		&i.RequestedByAgentID,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT a.id, a.workspace_id, a.task_id, a.execution_id, a.requested_by_agent_id, a.title, a.description, a.payload, a.decision, a.decided_by_user_id, a.decided_at, a.created_at, ag.name AS requested_by_name
FROM approvals a
LEFT JOIN agents ag ON ag.id = a.requested_by_agent_id
WHERE a.id = $1
`

type GetApprovalRow struct {
	ID                 uuid.UUID            `json:"id"`
	WorkspaceID        uuid.UUID            `json:"workspace_id"`
	TaskID             uuid.NullUUID        `json:"task_id"`
	ExecutionID        uuid.NullUUID        `json:"execution_id"`
	RequestedByAgentID uuid.NullUUID        `json:"requested_by_agent_id"`
	Title              string               `json:"title"`
	Description        string               `json:"description"`
	Payload            []byte               `json:"payload"`
	Decision           NullApprovalDecision `json:"decision"`
	DecidedByUserID    uuid.NullUUID        `json:"decided_by_user_id"`
	DecidedAt          pgtype.Timestamptz   `json:"decided_at"`
	CreatedAt          pgtype.Timestamptz   `json:"created_at"`
	RequestedByName    pgtype.Text          `json:"requested_by_name"`
}

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (GetApprovalRow, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i GetApprovalRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ExecutionID,
		&i.RequestedByAgentID,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.RequestedByName,
	)
	return i, err
}

const getPendingApprovalForWorkspace = `-- name: GetPendingApprovalForWorkspace :one
SELECT a.id, a.workspace_id, a.task_id, a.execution_id, a.requested_by_agent_id, a.title, a.description, a.payload, a.decision, a.decided_by_user_id, a.decided_at, a.created_at, ag.name AS requested_by_name
FROM approvals a
LEFT JOIN agents ag ON ag.id = a.requested_by_agent_id
WHERE a.workspace_id = $1 AND a.decision IS NULL
ORDER BY a.created_at DESC
LIMIT 1
`

type GetPendingApprovalForWorkspaceRow struct {
	ID                 uuid.UUID            `json:"id"`
	WorkspaceID        uuid.UUID            `json:"workspace_id"`
	TaskID             uuid.NullUUID        `json:"task_id"`
	ExecutionID        uuid.NullUUID        `json:"execution_id"`
	RequestedByAgentID uuid.NullUUID        `json:"requested_by_agent_id"`
	Title              string               `json:"title"`
	Description        string               `json:"description"`
	Payload            []byte               `json:"payload"`
	Decision           NullApprovalDecision `json:"decision"`
	DecidedByUserID    uuid.NullUUID        `json:"decided_by_user_id"`
	DecidedAt          pgtype.Timestamptz   `json:"decided_at"`
	CreatedAt          pgtype.Timestamptz   `json:"created_at"`
	RequestedByName    pgtype.Text          `json:"requested_by_name"`
}

func (q *Queries) GetPendingApprovalForWorkspace(ctx context.Context, workspaceID uuid.UUID) (GetPendingApprovalForWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getPendingApprovalForWorkspace, workspaceID)
	var i GetPendingApprovalForWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ExecutionID,
		&i.RequestedByAgentID,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.RequestedByName,
	)
	return i, err
}
