// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (workspace_id, user_id, agent_id, device_id, approval_id, action, result, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	UserID      uuid.NullUUID `json:"user_id"`
	AgentID     uuid.NullUUID `json:"agent_id"`
	DeviceID    uuid.NullUUID `json:"device_id"`
	ApprovalID  uuid.NullUUID `json:"approval_id"`
	Action      string        `json:"action"`
	Result      string        `json:"result"`
	Metadata    []byte        `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.WorkspaceID,
		arg.UserID,
		arg.AgentID,
		arg.DeviceID,
		arg.ApprovalID,
		arg.Action,
		arg.Result,
		arg.Metadata,
	)
	return err
}
