// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserIDByExternalIdentity = `-- name: GetUserIDByExternalIdentity :one
SELECT user_id
FROM external_identities
WHERE issuer = $1 AND subject = $2
`

type GetUserIDByExternalIdentityParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetUserIDByExternalIdentity(ctx context.Context, arg GetUserIDByExternalIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByExternalIdentity, arg.Issuer, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, email, display_name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaceMembershipsForUser = `-- name: ListWorkspaceMembershipsForUser :many
SELECT
  w.id AS workspace_id,
  w.name AS workspace_name,
  w.slug AS workspace_slug,
  wm.role,
  wm.joined_at
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.name, w.id
`

type ListWorkspaceMembershipsForUserRow struct {
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	WorkspaceName string             `json:"workspace_name"`
	WorkspaceSlug string             `json:"workspace_slug"`
	Role          string             `json:"role"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListWorkspaceMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspaceMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembershipsForUserRow{}
	for rows.Next() {
		var i ListWorkspaceMembershipsForUserRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
