// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getDevice = `-- name: GetDevice :one
SELECT id, name, role_label, status, cpu_percent, ram_percent, disk_percent
FROM devices
WHERE id = $1
`

type GetDeviceRow struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	RoleLabel   string       `json:"role_label"`
	Status      DeviceStatus `json:"status"`
	CpuPercent  int16        `json:"cpu_percent"`
	RamPercent  int16        `json:"ram_percent"`
	DiskPercent int16        `json:"disk_percent"`
}

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (GetDeviceRow, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i GetDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoleLabel,
		&i.Status,
		&i.CpuPercent,
		&i.RamPercent,
		&i.DiskPercent,
	)
	return i, err
}

const listDevicesForWorkspace = `-- name: ListDevicesForWorkspace :many
SELECT
  d.id, d.name, d.role_label, d.status, d.cpu_percent, d.ram_percent, d.disk_percent,
  COUNT(DISTINCT e.agent_id) FILTER (WHERE e.finished_at IS NULL) AS active_agent_count
FROM devices d
LEFT JOIN executions e ON e.device_id = d.id
WHERE d.workspace_id = $1
GROUP BY d.id
ORDER BY d.name
`

type ListDevicesForWorkspaceRow struct {
	ID               uuid.UUID    `json:"id"`
	Name             string       `json:"name"`
	RoleLabel        string       `json:"role_label"`
	Status           DeviceStatus `json:"status"`
	CpuPercent       int16        `json:"cpu_percent"`
	RamPercent       int16        `json:"ram_percent"`
	DiskPercent      int16        `json:"disk_percent"`
	ActiveAgentCount int64        `json:"active_agent_count"`
}

func (q *Queries) ListDevicesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListDevicesForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevicesForWorkspaceRow{}
	for rows.Next() {
		var i ListDevicesForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleLabel,
			&i.Status,
			&i.CpuPercent,
			&i.RamPercent,
			&i.DiskPercent,
			&i.ActiveAgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
