// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRole string

const (
	AgentRoleDEV    AgentRole = "DEV"
	AgentRoleQA     AgentRole = "QA"
	AgentRoleDEVOPS AgentRole = "DEVOPS"
)

func (e *AgentRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRole(s)
	case string:
		*e = AgentRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRole: %T", src)
	}
	return nil
}

type NullAgentRole struct {
	AgentRole AgentRole `json:"agent_role"`
	Valid     bool      `json:"valid"` // Valid is true if AgentRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRole) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRole), nil
}

type AgentRuntimeStatus string

const (
	AgentRuntimeStatusRUNNING AgentRuntimeStatus = "RUNNING"
	AgentRuntimeStatusWARNING AgentRuntimeStatus = "WARNING"
	AgentRuntimeStatusIDLE    AgentRuntimeStatus = "IDLE"
	AgentRuntimeStatusERROR   AgentRuntimeStatus = "ERROR"
	AgentRuntimeStatusOFFLINE AgentRuntimeStatus = "OFFLINE"
)

func (e *AgentRuntimeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentRuntimeStatus(s)
	case string:
		*e = AgentRuntimeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentRuntimeStatus: %T", src)
	}
	return nil
}

type NullAgentRuntimeStatus struct {
	AgentRuntimeStatus AgentRuntimeStatus `json:"agent_runtime_status"`
	Valid              bool               `json:"valid"` // Valid is true if AgentRuntimeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentRuntimeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AgentRuntimeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentRuntimeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentRuntimeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentRuntimeStatus), nil
}

type ApprovalDecision string

const (
	ApprovalDecisionAPPROVED ApprovalDecision = "APPROVED"
	ApprovalDecisionREJECTED ApprovalDecision = "REJECTED"
)

func (e *ApprovalDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalDecision(s)
	case string:
		*e = ApprovalDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalDecision: %T", src)
	}
	return nil
}

type NullApprovalDecision struct {
	ApprovalDecision ApprovalDecision `json:"approval_decision"`
	Valid            bool             `json:"valid"` // Valid is true if ApprovalDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalDecision) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalDecision), nil
}

type DeviceStatus string

const (
	DeviceStatusONLINE  DeviceStatus = "ONLINE"
	DeviceStatusOFFLINE DeviceStatus = "OFFLINE"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

type ExecutionNodeStatus string

const (
	ExecutionNodeStatusDONE    ExecutionNodeStatus = "DONE"
	ExecutionNodeStatusACTIVE  ExecutionNodeStatus = "ACTIVE"
	ExecutionNodeStatusPENDING ExecutionNodeStatus = "PENDING"
)

func (e *ExecutionNodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionNodeStatus(s)
	case string:
		*e = ExecutionNodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionNodeStatus: %T", src)
	}
	return nil
}

type NullExecutionNodeStatus struct {
	ExecutionNodeStatus ExecutionNodeStatus `json:"execution_node_status"`
	Valid               bool                `json:"valid"` // Valid is true if ExecutionNodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionNodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionNodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionNodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionNodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionNodeStatus), nil
}

type TaskStatus string

const (
	TaskStatusQUEUED     TaskStatus = "QUEUED"
	TaskStatusINPROGRESS TaskStatus = "IN_PROGRESS"
	TaskStatusCOMPLETED  TaskStatus = "COMPLETED"
	TaskStatusFAILED     TaskStatus = "FAILED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Agent struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Role        AgentRole          `json:"role"`
	Model       string             `json:"model"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Approval struct {
	ID                 uuid.UUID            `json:"id"`
	WorkspaceID        uuid.UUID            `json:"workspace_id"`
	TaskID             uuid.NullUUID        `json:"task_id"`
	ExecutionID        uuid.NullUUID        `json:"execution_id"`
	RequestedByAgentID uuid.NullUUID        `json:"requested_by_agent_id"`
	Title              string               `json:"title"`
	Description        string               `json:"description"`
	Payload            []byte               `json:"payload"`
	Decision           NullApprovalDecision `json:"decision"`
	DecidedByUserID    uuid.NullUUID        `json:"decided_by_user_id"`
	DecidedAt          pgtype.Timestamptz   `json:"decided_at"`
	CreatedAt          pgtype.Timestamptz   `json:"created_at"`
}

type Artifact struct {
	ID             uuid.UUID          `json:"id"`
	TaskID         uuid.UUID          `json:"task_id"`
	ExecutionID    uuid.NullUUID      `json:"execution_id"`
	Kind           string             `json:"kind"`
	FilePath       pgtype.Text        `json:"file_path"`
	StorageUrl     pgtype.Text        `json:"storage_url"`
	ContentPreview pgtype.Text        `json:"content_preview"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.NullUUID      `json:"user_id"`
	AgentID     uuid.NullUUID      `json:"agent_id"`
	DeviceID    uuid.NullUUID      `json:"device_id"`
	ApprovalID  uuid.NullUUID      `json:"approval_id"`
	Action      string             `json:"action"`
	Result      string             `json:"result"`
	Metadata    []byte             `json:"metadata"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type CredentialsMetadatum struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	DeviceID    uuid.NullUUID      `json:"device_id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	ExternalRef string             `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RotatedAt   pgtype.Timestamptz `json:"rotated_at"`
}

type Device struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Name            string             `json:"name"`
	RoleLabel       string             `json:"role_label"`
	Status          DeviceStatus       `json:"status"`
	CpuPercent      int16              `json:"cpu_percent"`
	RamPercent      int16              `json:"ram_percent"`
	DiskPercent     int16              `json:"disk_percent"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type DeviceCapability struct {
	DeviceID   uuid.UUID `json:"device_id"`
	Capability string    `json:"capability"`
	Enabled    bool      `json:"enabled"`
}

type Execution struct {
	ID              uuid.UUID          `json:"id"`
	TaskStepID      uuid.UUID          `json:"task_step_id"`
	AgentID         uuid.UUID          `json:"agent_id"`
	DeviceID        uuid.NullUUID      `json:"device_id"`
	AttemptNumber   int32              `json:"attempt_number"`
	Status          AgentRuntimeStatus `json:"status"`
	ProgressPercent pgtype.Int4        `json:"progress_percent"`
	CurrentActivity string             `json:"current_activity"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

type ExecutionEvent struct {
	ID          uuid.UUID          `json:"id"`
	TaskID      uuid.UUID          `json:"task_id"`
	ExecutionID uuid.NullUUID      `json:"execution_id"`
	AgentID     uuid.NullUUID      `json:"agent_id"`
	EventType   string             `json:"event_type"`
	Message     string             `json:"message"`
	Highlighted bool               `json:"highlighted"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type ExternalIdentity struct {
	Issuer    string             `json:"issuer"`
	Subject   string             `json:"subject"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	RepoUrl     pgtype.Text        `json:"repo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Code            string             `json:"code"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Status          TaskStatus         `json:"status"`
	ProgressPercent int32              `json:"progress_percent"`
	CreatedByUserID uuid.NullUUID      `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TaskStep struct {
	ID            uuid.UUID           `json:"id"`
	TaskID        uuid.UUID           `json:"task_id"`
	SequenceOrder int32               `json:"sequence_order"`
	Label         string              `json:"label"`
	Status        ExecutionNodeStatus `json:"status"`
	AgentID       uuid.NullUUID       `json:"agent_id"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
