// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTasksByProject(ctx context.Context, projectID uuid.UUID) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error)
	GetApproval(ctx context.Context, id uuid.UUID) (GetApprovalRow, error)
	GetDevice(ctx context.Context, id uuid.UUID) (GetDeviceRow, error)
	GetFirstProjectForWorkspace(ctx context.Context, workspaceID uuid.UUID) (Project, error)
	GetFirstWorkspace(ctx context.Context) (Workspace, error)
	GetPendingApprovalForWorkspace(ctx context.Context, workspaceID uuid.UUID) (GetPendingApprovalForWorkspaceRow, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetUserIDByExternalIdentity(ctx context.Context, arg GetUserIDByExternalIdentityParams) (uuid.UUID, error)
	GetUserProfile(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertExecutionEvent(ctx context.Context, arg InsertExecutionEventParams) (ExecutionEvent, error)
	ListActiveAgentsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListActiveAgentsForWorkspaceRow, error)
	ListAgentsForTask(ctx context.Context, taskID uuid.UUID) ([]ListAgentsForTaskRow, error)
	ListDevicesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListDevicesForWorkspaceRow, error)
	ListExecutionEventsByTask(ctx context.Context, taskID uuid.UUID) ([]ExecutionEvent, error)
	ListTaskStepsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskStep, error)
	ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]ListTasksByProjectRow, error)
	ListWorkspaceMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspaceMembershipsForUserRow, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	// Consultas usadas só pelo simulador de eventos de demonstração (DEMO_SIMULATOR=true).
	UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error)
	UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error)
	UpsertApproval(ctx context.Context, arg UpsertApprovalParams) (Approval, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	UpsertDeviceCapability(ctx context.Context, arg UpsertDeviceCapabilityParams) error
	UpsertExecution(ctx context.Context, arg UpsertExecutionParams) (Execution, error)
	UpsertExecutionEvent(ctx context.Context, arg UpsertExecutionEventParams) (ExecutionEvent, error)
	UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) error
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
	UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error)
	UpsertTaskStep(ctx context.Context, arg UpsertTaskStepParams) (TaskStep, error)
	// Upserts idempotentes usados só por cmd/seed. IDs vêm fixos do chamador.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error)
	UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) error
}

var _ Querier = (*Queries)(nil)
