// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (id, workspace_id, name, role, model, is_active) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, role = EXCLUDED.role, model = EXCLUDED.model, is_active = EXCLUDED.is_active
RETURNING id, workspace_id, name, role, model, is_active, created_at
`

type UpsertAgentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Role        AgentRole `json:"role"`
	Model       string    `json:"model"`
	IsActive    bool      `json:"is_active"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, upsertAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Role,
		arg.Model,
		arg.IsActive,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Role,
		&i.Model,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertApproval = `-- name: UpsertApproval :one
INSERT INTO approvals (id, workspace_id, task_id, execution_id, requested_by_agent_id, title, description, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, payload = EXCLUDED.payload
RETURNING id, workspace_id, task_id, execution_id, requested_by_agent_id, title, description, payload, decision, decided_by_user_id, decided_at, created_at
`

type UpsertApprovalParams struct {
	ID                 uuid.UUID     `json:"id"`
	WorkspaceID        uuid.UUID     `json:"workspace_id"`
	TaskID             uuid.NullUUID `json:"task_id"`
	ExecutionID        uuid.NullUUID `json:"execution_id"`
	RequestedByAgentID uuid.NullUUID `json:"requested_by_agent_id"`
	Title              string        `json:"title"`
	Description        string        `json:"description"`
	Payload            []byte        `json:"payload"`
}

func (q *Queries) UpsertApproval(ctx context.Context, arg UpsertApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, upsertApproval,
		arg.ID,
		arg.WorkspaceID,
		arg.TaskID,
		arg.ExecutionID,
		arg.RequestedByAgentID,
		arg.Title,
		arg.Description,
		arg.Payload,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ExecutionID,
		&i.RequestedByAgentID,
		&i.Title,
		&i.Description,
		&i.Payload,
		&i.Decision,
		&i.DecidedByUserID,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (id, workspace_id, name, role_label, status, cpu_percent, ram_percent, disk_percent, last_heartbeat_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, role_label = EXCLUDED.role_label, status = EXCLUDED.status,
  cpu_percent = EXCLUDED.cpu_percent, ram_percent = EXCLUDED.ram_percent, disk_percent = EXCLUDED.disk_percent,
  last_heartbeat_at = EXCLUDED.last_heartbeat_at
RETURNING id, workspace_id, name, role_label, status, cpu_percent, ram_percent, disk_percent, last_heartbeat_at, created_at
`

type UpsertDeviceParams struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Name            string             `json:"name"`
	RoleLabel       string             `json:"role_label"`
	Status          DeviceStatus       `json:"status"`
	CpuPercent      int16              `json:"cpu_percent"`
	RamPercent      int16              `json:"ram_percent"`
	DiskPercent     int16              `json:"disk_percent"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.RoleLabel,
		arg.Status,
		arg.CpuPercent,
		arg.RamPercent,
		arg.DiskPercent,
		arg.LastHeartbeatAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.RoleLabel,
		&i.Status,
		&i.CpuPercent,
		&i.RamPercent,
		&i.DiskPercent,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDeviceCapability = `-- name: UpsertDeviceCapability :exec
INSERT INTO device_capabilities (device_id, capability, enabled) VALUES ($1, $2, $3)
ON CONFLICT (device_id, capability) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertDeviceCapabilityParams struct {
	DeviceID   uuid.UUID `json:"device_id"`
	Capability string    `json:"capability"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) UpsertDeviceCapability(ctx context.Context, arg UpsertDeviceCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceCapability, arg.DeviceID, arg.Capability, arg.Enabled)
	return err
}

const upsertExecution = `-- name: UpsertExecution :one
INSERT INTO executions (id, task_step_id, agent_id, device_id, attempt_number, status, progress_percent, current_activity, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
  status = EXCLUDED.status, progress_percent = EXCLUDED.progress_percent,
  current_activity = EXCLUDED.current_activity, finished_at = EXCLUDED.finished_at
RETURNING id, task_step_id, agent_id, device_id, attempt_number, status, progress_percent, current_activity, started_at, finished_at
`

type UpsertExecutionParams struct {
	ID              uuid.UUID          `json:"id"`
	TaskStepID      uuid.UUID          `json:"task_step_id"`
	AgentID         uuid.UUID          `json:"agent_id"`
	DeviceID        uuid.NullUUID      `json:"device_id"`
	AttemptNumber   int32              `json:"attempt_number"`
	Status          AgentRuntimeStatus `json:"status"`
	ProgressPercent pgtype.Int4        `json:"progress_percent"`
	CurrentActivity string             `json:"current_activity"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpsertExecution(ctx context.Context, arg UpsertExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, upsertExecution,
		arg.ID,
		arg.TaskStepID,
		arg.AgentID,
		arg.DeviceID,
		arg.AttemptNumber,
		arg.Status,
		arg.ProgressPercent,
		arg.CurrentActivity,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.TaskStepID,
		&i.AgentID,
		&i.DeviceID,
		&i.AttemptNumber,
		&i.Status,
		&i.ProgressPercent,
		&i.CurrentActivity,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const upsertExecutionEvent = `-- name: UpsertExecutionEvent :one
INSERT INTO execution_events (id, task_id, execution_id, agent_id, event_type, message, highlighted, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, highlighted = EXCLUDED.highlighted
RETURNING id, task_id, execution_id, agent_id, event_type, message, highlighted, occurred_at
`

type UpsertExecutionEventParams struct {
	ID          uuid.UUID          `json:"id"`
	TaskID      uuid.UUID          `json:"task_id"`
	ExecutionID uuid.NullUUID      `json:"execution_id"`
	AgentID     uuid.NullUUID      `json:"agent_id"`
	EventType   string             `json:"event_type"`
	Message     string             `json:"message"`
	Highlighted bool               `json:"highlighted"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) UpsertExecutionEvent(ctx context.Context, arg UpsertExecutionEventParams) (ExecutionEvent, error) {
	row := q.db.QueryRow(ctx, upsertExecutionEvent,
		arg.ID,
		arg.TaskID,
		arg.ExecutionID,
		arg.AgentID,
		arg.EventType,
		arg.Message,
		arg.Highlighted,
		arg.OccurredAt,
	)
	var i ExecutionEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.AgentID,
		&i.EventType,
		&i.Message,
		&i.Highlighted,
		&i.OccurredAt,
	)
	return i, err
}

const upsertExternalIdentity = `-- name: UpsertExternalIdentity :exec
INSERT INTO external_identities (issuer, subject, user_id) VALUES ($1, $2, $3)
ON CONFLICT (issuer, subject) DO UPDATE SET user_id = EXCLUDED.user_id
`

type UpsertExternalIdentityParams struct {
	Issuer  string    `json:"issuer"`
	Subject string    `json:"subject"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertExternalIdentity, arg.Issuer, arg.Subject, arg.UserID)
	return err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, workspace_id, name, slug, repo_url) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, repo_url = EXCLUDED.repo_url
RETURNING id, workspace_id, name, slug, repo_url, created_at
`

type UpsertProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	RepoUrl     pgtype.Text `json:"repo_url"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.RepoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTask = `-- name: UpsertTask :one
INSERT INTO tasks (id, project_id, code, title, description, status, progress_percent, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description, status = EXCLUDED.status,
  progress_percent = EXCLUDED.progress_percent
RETURNING id, project_id, code, title, description, status, progress_percent, created_by_user_id, created_at, updated_at
`

type UpsertTaskParams struct {
	ID              uuid.UUID     `json:"id"`
	ProjectID       uuid.UUID     `json:"project_id"`
	Code            string        `json:"code"`
	Title           string        `json:"title"`
	Description     string        `json:"description"`
	Status          TaskStatus    `json:"status"`
	ProgressPercent int32         `json:"progress_percent"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, upsertTask,
		arg.ID,
		arg.ProjectID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ProgressPercent,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ProgressPercent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTaskStep = `-- name: UpsertTaskStep :one
INSERT INTO task_steps (id, task_id, sequence_order, label, status, agent_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, status = EXCLUDED.status, agent_id = EXCLUDED.agent_id
RETURNING id, task_id, sequence_order, label, status, agent_id
`

type UpsertTaskStepParams struct {
	ID            uuid.UUID           `json:"id"`
	TaskID        uuid.UUID           `json:"task_id"`
	SequenceOrder int32               `json:"sequence_order"`
	Label         string              `json:"label"`
	Status        ExecutionNodeStatus `json:"status"`
	AgentID       uuid.NullUUID       `json:"agent_id"`
}

func (q *Queries) UpsertTaskStep(ctx context.Context, arg UpsertTaskStepParams) (TaskStep, error) {
	row := q.db.QueryRow(ctx, upsertTaskStep,
		arg.ID,
		arg.TaskID,
		arg.SequenceOrder,
		arg.Label,
		arg.Status,
		arg.AgentID,
	)
	var i TaskStep
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SequenceOrder,
		&i.Label,
		&i.Status,
		&i.AgentID,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (id, email, display_name) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, display_name = EXCLUDED.display_name
RETURNING id, email, display_name, created_at
`

type UpsertUserParams struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
}

// Upserts idempotentes usados só por cmd/seed. IDs vêm fixos do chamador.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (id, name, slug) VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug
RETURNING id, name, slug, created_at
`

type UpsertWorkspaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO NOTHING
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}
