// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulator.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertExecutionEvent = `-- name: InsertExecutionEvent :one
INSERT INTO execution_events (task_id, execution_id, agent_id, event_type, message, highlighted)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_id, execution_id, agent_id, event_type, message, highlighted, occurred_at
`

type InsertExecutionEventParams struct {
	TaskID      uuid.UUID     `json:"task_id"`
	ExecutionID uuid.NullUUID `json:"execution_id"`
	AgentID     uuid.NullUUID `json:"agent_id"`
	EventType   string        `json:"event_type"`
	Message     string        `json:"message"`
	Highlighted bool          `json:"highlighted"`
}

func (q *Queries) InsertExecutionEvent(ctx context.Context, arg InsertExecutionEventParams) (ExecutionEvent, error) {
	row := q.db.QueryRow(ctx, insertExecutionEvent,
		arg.TaskID,
		arg.ExecutionID,
		arg.AgentID,
		arg.EventType,
		arg.Message,
		arg.Highlighted,
	)
	var i ExecutionEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExecutionID,
		&i.AgentID,
		&i.EventType,
		&i.Message,
		&i.Highlighted,
		&i.OccurredAt,
	)
	return i, err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :one

UPDATE tasks SET progress_percent = $2, status = $3 WHERE id = $1
RETURNING id, project_id, code, title, description, status, progress_percent, created_by_user_id, created_at, updated_at
`

type UpdateTaskProgressParams struct {
	ID              uuid.UUID  `json:"id"`
	ProgressPercent int32      `json:"progress_percent"`
	Status          TaskStatus `json:"status"`
}

// Consultas usadas só pelo simulador de eventos de demonstração (DEMO_SIMULATOR=true).
func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskProgress, arg.ID, arg.ProgressPercent, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ProgressPercent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
