// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT count(*) FROM tasks WHERE project_id = $1
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, code, title, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, code, title, description, status, progress_percent, created_by_user_id, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID       uuid.UUID     `json:"project_id"`
	Code            string        `json:"code"`
	Title           string        `json:"title"`
	CreatedByUserID uuid.NullUUID `json:"created_by_user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Code,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ProgressPercent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, project_id, code, title, description, status, progress_percent, created_by_user_id, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ProgressPercent,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsForTask = `-- name: ListAgentsForTask :many
SELECT
  a.id, a.name, a.role, a.model,
  d.name AS machine_name,
  e.status AS runtime_status,
  e.progress_percent,
  e.current_activity
FROM task_steps ts
JOIN LATERAL (
  SELECT id, task_step_id, agent_id, device_id, attempt_number, status, progress_percent, current_activity, started_at, finished_at FROM executions ex WHERE ex.task_step_id = ts.id ORDER BY ex.started_at DESC LIMIT 1
) e ON true
JOIN agents a ON a.id = e.agent_id
LEFT JOIN devices d ON d.id = e.device_id
WHERE ts.task_id = $1
ORDER BY ts.sequence_order
`

type ListAgentsForTaskRow struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Role            AgentRole          `json:"role"`
	Model           string             `json:"model"`
	MachineName     pgtype.Text        `json:"machine_name"`
	RuntimeStatus   AgentRuntimeStatus `json:"runtime_status"`
	ProgressPercent pgtype.Int4        `json:"progress_percent"`
	CurrentActivity string             `json:"current_activity"`
}

func (q *Queries) ListAgentsForTask(ctx context.Context, taskID uuid.UUID) ([]ListAgentsForTaskRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForTaskRow{}
	for rows.Next() {
		var i ListAgentsForTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Model,
			&i.MachineName,
			&i.RuntimeStatus,
			&i.ProgressPercent,
			&i.CurrentActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionEventsByTask = `-- name: ListExecutionEventsByTask :many
SELECT id, task_id, execution_id, agent_id, event_type, message, highlighted, occurred_at FROM execution_events WHERE task_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListExecutionEventsByTask(ctx context.Context, taskID uuid.UUID) ([]ExecutionEvent, error) {
	rows, err := q.db.Query(ctx, listExecutionEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionEvent{}
	for rows.Next() {
		var i ExecutionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ExecutionID,
			&i.AgentID,
			&i.EventType,
			&i.Message,
			&i.Highlighted,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskStepsByTask = `-- name: ListTaskStepsByTask :many
SELECT id, task_id, sequence_order, label, status, agent_id FROM task_steps WHERE task_id = $1 ORDER BY sequence_order
`

func (q *Queries) ListTaskStepsByTask(ctx context.Context, taskID uuid.UUID) ([]TaskStep, error) {
	rows, err := q.db.Query(ctx, listTaskStepsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStep{}
	for rows.Next() {
		var i TaskStep
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SequenceOrder,
			&i.Label,
			&i.Status,
			&i.AgentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT
  t.id, t.code, t.title, t.status, t.progress_percent,
  COUNT(DISTINCT e.agent_id) FILTER (WHERE e.finished_at IS NULL) AS active_agent_count
FROM tasks t
LEFT JOIN task_steps ts ON ts.task_id = t.id
LEFT JOIN executions e ON e.task_step_id = ts.id
WHERE t.project_id = $1
GROUP BY t.id
ORDER BY t.created_at DESC
`

type ListTasksByProjectRow struct {
	ID               uuid.UUID  `json:"id"`
	Code             string     `json:"code"`
	Title            string     `json:"title"`
	Status           TaskStatus `json:"status"`
	ProgressPercent  int32      `json:"progress_percent"`
	ActiveAgentCount int64      `json:"active_agent_count"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByProjectRow{}
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Status,
			&i.ProgressPercent,
			&i.ActiveAgentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
