// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getFirstProjectForWorkspace = `-- name: GetFirstProjectForWorkspace :one
SELECT id, workspace_id, name, slug, repo_url, created_at FROM projects WHERE workspace_id = $1 ORDER BY created_at LIMIT 1
`

func (q *Queries) GetFirstProjectForWorkspace(ctx context.Context, workspaceID uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getFirstProjectForWorkspace, workspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstWorkspace = `-- name: GetFirstWorkspace :one
SELECT id, name, slug, created_at FROM workspaces ORDER BY created_at LIMIT 1
`

func (q *Queries) GetFirstWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRow(ctx, getFirstWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, slug, created_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
